version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongo-data:/data/db

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # 데이터 영속화

volumes:
  mongo-data:
  redis-data:
